apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
  namespace: monitoring
type: Opaque
stringData:
  # Replace with your Discord webhook URL.
  # To get one: Discord server → channel settings → Integrations → Webhooks → New Webhook → Copy URL.
  # Format: https://discord.com/api/webhooks/{id}/{token}
  webhook-url: "https://discordapp.com/api/webhooks/1488566541720227951/T2zLWXuCrTJrOA6wLl0EyjcwBZltNY6RZ5aSXkH8WgdmlpWHhQbClVX-wv4PZ9ZeZz08"
