apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 18.2.0
    helm:
      values: |
        auth:
          postgresPassword: "mysecretpassword"
          database: "tododb"
        primary:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          initdb:
            scripts:
              01-init-analytics.sql: |
                CREATE DATABASE analytics_db;
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true