apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics-worker
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/potdartapan/gitops-project.git
    targetRevision: HEAD
    path: k8s/apps/analytics-worker
    helm:
      parameters:
        - name: image.repository
          value: potdartapan/analytics-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
