apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      monitoring: "true"
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    any: true
