appName: "todo-app"
replicaCount: 1
image:
  repository: potdartapan/todo-app # Your DockerHub Username
  pullPolicy: Always
  tag: "5d781754c410ff0fc5f41502dbb514a0852b2322" # Will be overridden by GitHub Actions
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
env:
  DB_HOST: "postgres-postgresql"
  REDIS_HOST: "redis-master"
