appName: "todo-app"
replicaCount: 1
image:
  repository: potdartapan/todo-app # Your DockerHub Username
  pullPolicy: Always
  tag: "733a2fa262e19a1d212d0f927f6df838e78ac7be" # Will be overridden by GitHub Actions
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
env:
  DB_HOST: "postgres-postgresql"
  REDIS_HOST: "redis-master"
